### ISSUE TITLE
re-target for ARM variants.

### ISSUE THREAD

**Issue by donwade** [antony-jr/insight#3] opened 2019-06-05 00:25 UTC
Your x86 insight version works very well, better than other peoples efforts.
I am unable to reconstruct your build from scratch as i'd like to change the configure option to --target=arm-linux-gnueabi
Can you rebuild a binary and post an ARM variation alongside your x86 implementation?

**Comment by antony-jr** [comment] 2019-06-05 02:10
I will get it a try but I'm no expert in this.

**Comment by donwade** [comment] 2019-06-05 16:31
Actually, where did you get the source code from? I’d really like to get your version.
 I notice that the gdb  version is up to 8.x and nowhere on the internet can I find anyone who’s done that.

**Comment by antony-jr** [comment] 2019-06-05 16:39
The upstream [repo]( https://sourceware.org/git/?p=insight.git) has a submodule to this specific [binutils-gdb](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git) which I think is maintained by redhat  , The upstream repo builds gdb from source , This is all thanks to redhat developers who still support this software.

**Comment by antony-jr** [comment] 2019-06-06 05:29
Okay, I think it is possible to compile this using docker , but it is gonna take a while. So please wait. I might also release for **i386 , x86_64 , arm32v7 , and arm64v8**. The problem is that the deploy tools used to create the AppImage is only available for i386 and x86_64. So I also need to compile those from source in the docker image itself. So this is a lot of work.

**Comment by donwade** [comment] 2019-06-06 13:34
I think you’ll still be ok as the executable is still a x86 binary that merely knows how to understand arm targets.... docker could never know about the “arm” aspect.

If you could document all the steps you did to get this working I would appreciate it, as I’ll try to reproduce your work.

No rush for this. Everyone only has so much free time to do more fun things.

**Comment by antony-jr** [comment] 2019-06-06 13:38
> If you could document all the steps you did to get this working I would appreciate it, as I’ll try to reproduce your work.

I can but its very hard coded to ubuntu trusty. For now you can look at .travis.yml

**Comment by antony-jr** [comment] 2019-06-07 07:24
> I think you’ll still be ok as the executable is still a x86 binary that merely knows how to understand arm targets.... docker could never know about the “arm” aspect.

I think you can only debug ARM binaries when you have arm based operating system which also requires a ARM processor, with current build of Insight I can see the instructions but I can't execute those binaries because you need a ARM processor to do that. What are you trying to do? Can please elaborate a little more?

**Comment by donwade** [comment] 2019-06-07 14:11
I have a raspberry Pi which is arm based, so I attach a insight debugger that runs on my Dell laptop that has Ubuntu x86 on it. 
So the insight debugger is a cross compiled binary that runs on a pentium host and knows how to speak to an arm target. 
So the instructions to build a cross debugger is real simple.

I’ll send you those instructions in a sec when I hop on my laptop....

**Comment by antony-jr** [comment] 2019-06-07 14:34
So you want insight for 32 bit operating system?

**Comment by donwade** [comment] 2019-06-07 15:11
The insight binary will be no different that the one you currently provide, that is to say that it will be an 64 bit pentium executable.... however, when it is being built (via your magic), it will be told to understand how to talk to a 32 bit arm target.
so, give this websit s a read thru on how they make insight run on any 64 bit linux HOST and have the ability to understand the arm TARGET.
Debugging Embedded Linux with GDBserver and Insight (gdb GUI)

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Debugging Embedded Linux with GDBserver and Insight (gdb GUI)

Although it it sometimes possible to debug applications using GDB (The GNU Debugger) on the target boards, there...
 |

 |

 |





I already have done this and it works ok. I can use my bionic-Ubuntu 64 bit laptop to talk to my 32 bit arm TARGET.
What NOBODY has, is the magic that you have. The gdb debugger version (version 8+) that you provide is so far ahead of all insight debuggers I know of (6/7) . Moving the gdb debugger from 6/7 to 8 is not trivial but you seemed to have done it.

So I don't know how you have done the new gdb integration into insight. 

    On Friday, June 7, 2019, 10:34:44 a.m. EDT, Antony jr <notifications@github.com> wrote:  
 
 
So you want insight for 32 bit operating system?

**Comment by antony-jr** [comment] 2019-07-30 04:06
@donwade sorry to message you back this late. But I cannot see the links you wrote in the email when viewed on github. Please resend the links directly from github.

**Comment by donwade** [comment] 2019-07-30 12:08
https://www.cnx-software.com/2012/01/31/debugging-embedded-linux-with-gdbserver-and-insight-gdb-gui/

**Comment by antony-jr** [comment] 2021-05-31 17:49
@donwade Can you please test the development builds -> https://github.com/antony-jr/insight/releases/download/development/Insight-arm-linux-gnueabi-8180966-x86_64.AppImage

**Comment by antony-jr** [comment] 2021-06-01 05:36
@donwade Please reopen this issue if the re-targeted build did not work for you. I'm closing this for now.

**Closed as completed by antony-jr** 2021-06-01 05:36 UTC
